### ISSUE TITLE
UnboundLocalError: local variable 'pagerank' referenced before assignment

### ISSUE THREAD

**Issue by yangzhenyu3** [ya332/PageRank#1]
When I make sample_input.txt as input file is OK. Everything is good.
But When I replace it with web-Google.txt, it show that UnboundLocalError: local variable 'pagerank' referenced before assignment.

I use python 3.6 and mrjob0.6.9.

Can you konw how to solve it?

**Comment by ya332** [comment]
Hello @a805814077, please make sure that the you run the `python preprocess.py` on the web-Google.txt first.

**Comment by yangzhenyu3** [comment]
Yeah. I'm sure I run the python preprocess.py. It give me a file named 'preprocessed_web-Google.txt'. But there are still mistakes.
First I run preprocess.py to produce 'preprocessed_web-Google.txt'. Then I run driver.py. At last I get 'UnboundLocalError: local variable 'pagerank' referenced before assignment.'

**Comment by yangzhenyu3** [comment]
Can you tell me your python verison 3.6 or 3.8?

**Comment by ya332** [comment]
Hey @a805814077, my Python is 3.6.5 and it works on my part. I am not sure what the problem is.

**Comment by ya332** [comment]
Fixed this by commit 3813693ce62c2135d1cb4c3cf9ef6c509b3f1360
